spring:
  application:
    name: rest-with-spring-java-henrique
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_java_henrique?useTimezone=true&serverTimezone=UTC
    username: root
    password: hmazon
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    # root: WARN
    br.com.mazonhenrique: DEBUG